name: tempo
description: "Activity tracking and task management app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_native: ^0.1.1       # Liquid Glass UI
  cupertino_icons: ^1.0.6
  gap: ^3.0.0
  intl: ^0.19.0
  adaptive_platform_ui: ^0.1.98
  glass: ^2.0.0+2                  # Хелпер для размытия фона (Glassmorphism)

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Database
  drift: ^2.14.0
  sqlite3_flutter_libs: ^0.5.18  # Критично для iOS!
  path_provider: ^2.1.2
  path: ^1.8.3
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.8
  drift_dev: ^2.14.0
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true # Нужно для некоторых фолбеков